<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=koi8-r">
    <title>оЮМЕКЭ СОПЮБКЕМХЪ ДКЪ ЙКХЕМРНБ УНЯРХМЦ-ОПНБЮИДЕПЮ BeGet. оПХЪРМНИ ПЮАНРШ.</title>
  <link rel="stylesheet" type="text/css" href="style/cp_style.css">
  </head>

 <body>
 <table class="main_t" align="center" border="0">
	<tr align="left">
              <td>
			<img src="images/lg.png">
		</td>
		<td>
			<div class="up">
			оЮМЕКЭ сОПЮБКЕМХЪ юЙЙЮСМРНЛ 
			</div>
		</td>
<td>
</td>
	</tr>
	<tr>
		<td width="350"><p>
бШ ЛНФЕРЕ НАПЮРХРЭЯЪ Б КЧАСЧ ХГ ЯКСФА МЮЬЕИ ЙНЛОЮМХХ ОН ХМРЕПЕЯСЧЫЕЛС бЮЯ БНОПНЯС,
ВЕПЕГ e-mail, ОН РЕКЕТНМС ХКХ ВЕПЕГ оЮМЕКЭ сОПЮБКЕМХЪ юЙЙЮСМРНЛ.<br>
<br><br>
    рЕУМХВЕЯЙЮЪ ОНДДЕПФЙЮ ОНКЭГНБЮРЕКЕИ - <a href="mailto: support@beget.ru">support@beget.ru</a> <br>
    яКСФАЮ ОН ПЮАНРЕ Я ДНЛЕММШЛХ ХЛЕМЮЛХ - <a href="mailto: domains@beget.ru">domains@beget.ru</a> <br>
    йКХЕМРЯЙЮЪ ЯКСФАЮ - <a href="mailto: clients@beget.ru">clients@beget.ru</a><br>
    тХМЮМЯНБШЕ БНОПНЯШ (АСУЦЮКРЕПХЪ) - <a href="mailto: billing@beget.ru">billing@beget.ru</a><br>
    оЮПРМЕПЯЙНЕ ЯНРПСДМХВЕЯРБН - <a href="mailto: partner@beget.ru">partner@beget.ru</a><br>
    хМТНПЛЮЖХНММЮЪ ЯКСФАЮ - <a href="mailto: info@beget.ru">info@beget.ru</a><br>
    пСЙНБНДЯРБН ЙНЛОЮМХХ - <a href="mailto: manager@beget.ru">manager@beget.ru</a> <br>
</p>
</td>
		<td>
		<div class="f1"> 
				<form method="post">
					<table>
						<tr><td><span style="font-size: 11pt;">хЛЪ ОНКЭГНБЮРЕКЪ</span> </td><td><input type="text" name="name"></td></tr>
						<tr><td><span style="font-size: 11pt;">оЮПНКЭ</span></td><td><input type="password" name="password"></td></tr>
						<tr><td><input type="submit" name="submit" value="бУНД Б ОЮМЕКЭ СОПЮБКЕМХЪ"></td></tr>
					</table>
				</form>
		</div>
<p class="cl2">
<b>яКСФАЮ ОНДДЕПФЙХ:</b> 	 <br>	tel:+7 (812) 953-68-28; &nbsp;&nbsp;
email: <a href="mailto: support@beget.ru">support@beget.ru</a>;&nbsp;&nbsp;
icq: 963-141<br>
<br>
<b>тЮЙЯ:</b> +7 812 305-71-59</p>
		</td>
<td width="40">
</td>
	</tr>
<tr>
<td class="down" colspan="3">
<br>
<p class="line">

</p>

<p>
╘2007 ннн "аЕЦЕР". &nbsp; <a href="http://www.beget.ru">www.beget.ru</a><br>  
юДПЕЯ: 199034, яЮМЙР-оЕРЕПАСПЦ, 2-Ъ КХМХЪ бЮЯХКЭЕБЯЙНЦН
НЯРПНБЮ, ДНЛ.5, КХРЕП ю, ОНЛ. 11м; 
<br><br>
<a href="http://www.beget.ru/host.html">пЮГЛЕЫЕМХЕ ЯЮИРНБ</a>  -  <a href="http://www.beget.ru/regdom.html">пЕЦХЯРПЮЖХЪ ДНЛЕМНБ</a> - <a href="http://www.beget.ru/vip.html">VIP - УНЯРХМЦ</a> - <a href="http://www.beget.ru/arenda.html">юПЕМДЮ БШДЕКЕММШУ ЯЕПБЕПНБ</a> 
</p>
</td>
</tr>
	
 </table>

 </body>
</html>
